---

- name: Install redis-server
  apt: pkg=redis-server state=present

- name: Redis config
  copy:
    src=redis.conf
    dest=/etc/redis/redis.conf
    mode=0644
  notify:
    - restart redis

- name: Start redis-server
  service: name=redis-server state=started
