---

- name: Install apt packages for python 
  apt: pkg={{ item }} 
  with_items: python_apt_dep

- name: Install Python libraries with pip
  pip: name={{ item.name }} version={{ item.version }}
  with_items: pip_pkgs
