---
- hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - vars/aws.yml

  tasks:
  # Instances
  - name: Teardown instances 
    ec2:
      key_name: "{{ default_key_name }}"
      instance_type: "{{ item.instance_type }}"
      image: "{{ default_ami }}"
      wait: no
      group: "{{ item.security_groups }}"
      exact_count: 0
      instance_tags:
        Name: "{{ item.name }}"
        env: "{{ env }}"
      count_tag:
        Name: "{{ item.name }}"
      vpc_subnet_id: "{{ subnet_id }}"
      region: "{{ region }}"
    with_items: ec2_instances
    register: launched_instances
    tags: ['ec2']

  # RDS
  # - name: Teardown RDS 
  #   rds:
  #     command: modify
  #     instance_name: "{{ item.name }}"
  #     instance_type: db.t2.micro
  #     region: "{{ region }}"
  #   with_items: rds_instances
  #   tags: ['rds']
